cost_function: schwefel    # options for cost function: sphere, schwefel
max_itr: 10000
x_initial: null    # a d-dimensional list, such as [1.0, -1.0], or null. If null, the x_initial will be a random point in the domain
convergence_threshold: 0.01